.circleci/config.yml
Before, we had not set up a CI service for the repository. When developers pushed their changes, they had no idea if they had broken the app or not. We made CircleCI run the entire suite whenever we added a change to GitHub.
=> 🔧 Make CircleCI run our tests when we push

.rspec
This is needed to remove the need to  always write "require
spec_helper" for every new test file that is written.
The side effect is that as a developer, you won't have to always write
the line "require spec_helper" at the top of every test file that you
write.
Co-authored-by: Rob Whittaker <rob@thoughtbot.com>
=> 🔧 Make spec_helper to be required

.circleci/config.yml, app/assets/config/manifest.js, bin/setup, db/schema.rb, spec/rails_helper.rb, spec/support/chromedriver.rb
Before, we had not set up the tests to run in a headless browser. The CI build failed as soon as we ran a system test. We made the tests run without the need for the browser chrome.
- Refactored the database setup.
- Dropped unnecessary JavaScript directory.
[Trello][]
[trello]: https://trello.com/c/vNjOSsLn/25-make-ci-run-with-an-image-with-a-browser
=> 🔧 Make system tests run in a headless browser

Procfile, bin/auto_migrate
Before, we had to run the migrations by hand whenever we deployed to Heroku. This opens up to potential errors. We made Heroku run the migrations every time we release.
=> 🔧 Make Heroku run migrations on release

config/environments/development.rb, config/environments/test.rb
Before, our environment files contained the comments provided by the Rails generator. These didn't add much value, only unnecessary noise to the files. We dropped all the unnecessary ones.
=> 🗑 Drop unnecessary comments from environment files

README.md, bin/deploy
Before, we were having to recall or look up the Heroku commands in order
to initiate a deplpy to the server.
This is intended to simplify the deployment process.
=> 🔧 Add deploy script

app/views/articles/new.html.erb
The article creation form wasn't looking nice. New changes have been
added to make it look better.
**Article creation form before the changes**
**Article creation form after the change**
=> 🎨 Style the new article creation form

app/views/layouts/application.html.erb, config/locales/en.yml
The title, user greeting and sign out button on the nav menu weren't
setup to have translations.
This change introduces translations for them.
=> 🌐 Add translations to the nav menu

app/views/layouts/application.html.erb
Before, we had the title leading no where. We have made a change to make
title lead to the root path when clicked.
=> ♻️  Change title to point to the root path

app/views/users/_form.html.erb, app/views/users/new.html.erb
The signup page looked awful and everything was all over the place.
We have moved the different elements on the page to make it look better.
Sign up page before the change:
Sign up page after the change:
=> 🎨 Style sign up page to have a consistent layout

app/views/layouts/application.html.erb
The sign-in link on the nav bar was slightly off, so things didn't look
good.
We have made changes to align the link with the rest of the items on the
nav bar so that it now looks good.
Sign-in link before the change:
Sign-in link after the change:
=> 🎨 Align sign in link on the nav bar

app/assets/stylesheets/application.tailwind.css, app/helpers/application_helper.rb, app/views/users/_form.html.erb, spec/helpers/application_helper_spec.rb
When a user attempts to sign up without providing email and password,
there were no validation errors displayed to notify them of the issue.
We have made changes to the UI so the user can get to know what went
wrong.
=> 🎨 Add validation errors on the sign up page

app/views/articles/show.html.erb
The article show page wasn't looking nice so we have moved the different
elements on the page to make it look better.
Show page before the changes
Show page after the changes
=> 🎨 Style article show page

app/views/passwords/new.html.erb
The forgot password page wasn't looking good. So we made some changes to
move the different elements on the page to be placed in the appropriate
place.
This greatly improves visibility.
Forgot password page before:
Forgot password page after:
=> 🎨 Style forgot password page

app/controllers/articles_controller.rb, app/models/article.rb, app/models/user.rb, db/migrate/20230505095856_add_user_to_article.rb, db/schema.rb, spec/models/article_spec.rb, spec/models/user_spec.rb, spec/system/user_creates_an_article_spec.rb
Before, any user could log in and be able to edit an article that they
didn't create.
We have made changes so that an article belongs to a user.
So, a user can only edit articles that they created.
=> ✨ Limit edit article to the user who created it

spec/system/user_edits_an_article_spec.rb
We had previously created a spec to describe the behavior when a user
decides to edit an article but changes their mind and clicks save
instead without editing the article.
However, we have currently removed this spec.
=> ♻️  Remove unused show unedited article spec

app/assets/stylesheets/application.tailwind.css, app/views/application/_flashes.html.erb
We have changed the flash message to be centered in the page.
The flash message was previously spanning the entire width of the page
=> 🎨 Restyle landing page flash message

app/views/articles/show.html.erb
We have eliminated the additional flash messages in the form, so now
only a single flash message is shown.
=> 🎨 Remove the extra flash message

.circleci/config.yml
There was no way for us to check our code styles without looking at
them.
We have added automated linting to run on the CI whenever we push a
commit.
=> 🔧 Add automated linting

.github/dependabot.yml
We have added dependabot to automate the process of checking our
dependencies for us.
Previously, we had to check our dependencies ourselves.
=> 🔧 Add dependabot

.github/dependabot.yml
We had a typo in the dependabot configuration. This was stopping
dependabot from running.
We fixed the typo so that dependabot runs properly.
=> 🐛 Fix typo in dependabot config

Gemfile.lock
Before, we included a bunch of Bundler platforms to allow us to package our Ruby gems across different operating systems. This specification is no longer necessary and started to cause issues with our CI service. We dropped the unnecessary Bundler platforms from the Gemfile.lock.
=> 🗑️ Drop unnecessary Bundler platforms

.circleci/config.yml
This was done to fix the issue of the CI failing to build and we were getting an
error with the installed version of Google Chrome.
This change should fix the issue and the CI should build successfully.
=> Bump circle ci browser tools from 1.4.3 to 1.4.5

app/views/layouts/application.html.erb
Previously, sign-in wasn't working. When clicked, nothing would happen.
It has been changed to be a link.
The sign-in link now works as expected when a user clicks on it.
=> 🐛 Change sign-in into a link

app/models/article_policy.rb, app/views/articles/_article.html.erb, app/views/articles/index.html.erb, app/views/articles/show.html.erb, spec/models/article_policy_spec.rb, spec/system/author_visits_an_author_profile_spec.rb, spec/system/guest_visits_an_author_profile_spec.rb, spec/system/guest_visits_the_home_page_spec.rb
Previously, the edit button was present on every article card.
We have now enhanced it to only display for the author of the
article.
This modification reduces confusion, ensuring users can only edit
articles they have authored.
=> ♻️  Improve edit button visibility

app/models/user.rb, app/views/application/_greeting.en.html.erb, app/views/layouts/application.html.erb
Formerly, signed-in users had to navigate through a drop down menu in
order to access their created articles.
Now, this information is directly accessible from the header.
This enhancement simplifies the process for users to navigate to their
created articles.
=> ✨ Add articles link on the header

app/javascript/application.js, app/views/layouts/application.html.erb, config/importmap.rb, config/locales/en.yml
Previously, signed-in users had to navigate through a drop-down menu to
view and create articles.
We've streamlined this process by introducing a direct link to the new
article page.
This change aims to simplify navigation and minimize the reliance on
JavaScript.
=> ♻️  Change articles link

.env.test, app/controllers/users_controller.rb, app/models/user.rb, app/views/application/_greeting.en.html.erb, app/views/users/_form.html.erb, db/migrate/20231201104328_add_name_to_users.rb, db/schema.rb, db/seeds.rb, spec/factories/clearance.rb, spec/models/user_spec.rb, spec/support/features/clearance_helpers.rb, spec/system/clearance/visitor_signs_up_spec.rb
Previously, the sign-up form collected only the user's email and
password.
We have extended this functionality to include the user's name.
This update enables us to personalize the user greeting upon sign-in
with their name.
=> ✨ Add name field to the sign-up form

app/assets/stylesheets/application.tailwind.css, app/views/application/_flashes.html.erb
Previously, the success alert appeared in red, causing visual confusion as it closely resembled the error alert.
We have changed the success alert colour to green to eliminate any potential confusion.
Older red success alert:
New green success alert:
=> 🎨 Change success alert colour to green

app/views/application/_greeting.en.html.erb
Previously, this was pointing to the user path and causing an unknown action error.
This has been fixed to point to the author path.
This gets rid of the error.
=> 🐛 Fix author link

README.md
Previously, the readme file was generic and it wasn't clear what the project was about.
Changes have been made to include information about the project and how to set up the project locally.
This should be more informative to a new person who stumbles on the project.
=> Change the readme file content

app/controllers/passwords_controller.rb, config/routes.rb, spec/system/clearance/visitor_updates_password_spec.rb
Previously, when a user attempted to reset their password, they were unable to successfully change it. 
We have made changes to make it possible for a user to reset their password.
=> Fix forgot password functionality

.circleci/config.yml
The circleci build was failing because the chrome version from browser tools 1.4.5 was causing an error: The requested URL returned error 404 for Chrome.
This was causing the build to not complete.
Browser tools 1.4.8 should fix the error.
=> Upgrade Circleci browser tools to 1.4.8

config/application.rb
The message below was coming up when a spec was run;
Dotenv::Railtie is deprecated! Use Dotenv::Rails instead.
This change helps to solve this.
=> Remove Railtie deprecation message

app/views/articles/show.html.erb, app/views/comments/_comment.html.erb, app/views/comments/edit.html.erb, app/views/comments/new.html.erb
The view that allows a user to provide feedback on a specific post was looking awful.
It has been styled to look more pleasant and to have a consistent user experience.
Comment view before
Comment view after
=> Style comment view

app/controllers/comments_controller.rb, app/models/comment.rb, config/locales/en.yml, spec/system/author_visits_the_home_page_spec.rb
Previously, the update logic did not account for cases where a comment edit was unsuccessful and this would result in errors and missing to provide feedback to the user.
This refactor ensures that the failed comment edits are properly handled.
This provides a better user experience and better error management.
=> Handle unsuccessful comment edit

app/controllers/comments_controller.rb, app/views/comments/_comment.html.erb, config/locales/en.yml, spec/system/author_visits_the_home_page_spec.rb
Previously, users could not delete comments they had added to a post.
This update introduces functionality allowing users to delete their own comments.
=> Enable comment deletion by the user

app/views/comments/_comment.html.erb
Previously, the comments view didn't properly account for dark mode, causing added comments to display poorly in this mode.
This refactor adjusts the comments view to ensure proper styling and readability when dark mode is enabled.
This improves the user experience.
Comments view before
Comments view after
=> Refactor comments view to support dark mode

app/views/articles/_article.html.erb, app/views/articles/index.html.erb
Refactored the article index to use the article partial, making the code cleaner and easier to maintain.
Article titles are now clickable, allowing users to view article details directly.
=> Refactor article index and make article title clickable

app/views/articles/show.html.erb, config/locales/en.yml, spec/system/user_creates_an_article_spec.rb
We have added the author's name and the article's creation date to provide additional context and to improve the user's understanding of the article's origin.
=> Add author name and Time stamp to articles

app/views/comments/_comments_section.html.erb
We had redundant code in both the comments section partial and the comments partial.
We have made changes to remove the extra code. This improves maintainability.
=> Refactor comments section
