Esseme/rumblr

- Gemfile
This was done to remove the many comments in the Gemfile
It makes the Gemfile more clean and readable
Co-authored: Rob Whittaker <rob@thoughtbot.com>
> 📇 Reword Gemfile

- .gitignore
- Gemfile
- Gemfile.lock
- Procfile.dev
- app/assets/config/manifest.js
- app/assets/stylesheets/application.tailwind.css
- app/views/layouts/application.html.erb
- bin/dev
- config/tailwind.config.js
This was done to make it easy and fast to add styling to different HTML
elements of the app.
It will assist in building responsive layouts.
> 🎨 Add TailwindCSS

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.tailwind.css
- app/controllers/articles_controller.rb
- app/models/article.rb
- app/views/articles/new.html.erb
- app/views/articles/show.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20220623155325_create_articles.rb
- spec/models/article_spec.rb
- spec/spec_helper.rb
- spec/system/user_creates_an_article_spec.rb
**Add article creation**
This feature is to enable this functionality for a user: 
when I have something to say, I want to put it on the internet so that everybody can see it
Co-authored-by: Rob Whittaker <rob@thoughtbot.com>
> ✨Add article creation

- app/views/articles/new.html.erb
- app/views/articles/show.html.erb
This was done to improve the UI of the form for article creation and the
display of the article.
> 🎨 Add styling to article creation

- app/assets/stylesheets/application.tailwind.css
- app/views/layouts/application.html.erb
- app/views/sessions/_form.html.erb
- app/views/sessions/new.html.erb
- config/locales/en.yml
Before, we used the Clearance gem's default styling from the
authentication flow.
This looked rather drab, and we wanted things to be prettier for
our visitors.
We added styles to the authentication flow to make this happen.
> 🎨 Add styles to the authentication flow

- app/assets/stylesheets/application.tailwind.css
- app/views/layouts/application.html.erb
- app/views/sessions/_form.html.erb
- app/views/sessions/new.html.erb
Before, the sign-in page had elements all over the place.
The sign-in page has been adjusted to make it look better and to improve
visibility
> 🎨 Style sign in page to have a consistent layout

- .circleci/config.yml
Circleci was working fine previously but an error came up. Our project
wasn't building successfully because of this, so this is meant to fix
the error.
> 🔧 Fix circleci issue

- app/assets/stylesheets/application.tailwind.css
- app/views/application/_flashes.html.erb
Before the flash messages weren't looking nice.
We have made some changes to make them look better.
> 🎨 Style flash messages

- .env.test
- .github/workflows/config.yml
- config/database.yml
We are exploring the option of using GitHub actions in order to automate
running of tests and building of the project whenever code is pushed to
GitHub and when a new PR is opened.
> 🔧 Add ci using github actions

- app/views/layouts/application.html.erb
The navigation menu wasn't styled and was looking awful. We moved the different
menu items so that it looks much better.
Nav menu before:
Nav menu after:
> 🎨 Style navigation menu

- app/controllers/articles_controller.rb
- app/views/articles/edit.html.erb
- app/views/articles/show.html.erb
- config/locales/en.yml
- spec/system/user_edits_an_article_spec.rb
Before, a user could only create a new article. Now, if the user isn't
happy with what their article, they are able to edit it.
> ✨ Add edit article

- app/controllers/articles_controller.rb
- app/views/articles/index.html.erb
- spec/factories/article.rb
- spec/system/user_articles_spec.rb
A logged in user is now able to view the list of articles that they have
created.
> ✨ Allow logged in user to view list of created articles

- app/controllers/articles_controller.rb
- app/models/article.rb
This was done to improve the readability of the code and consequently
make it easy to maintain
> ♻️  Add a previously_changed? method

- .env.test
- db/migrate/20230607085338_add_admin_to_user.rb
- db/schema.rb
- db/seeds.rb
Now, when the app is built, there will be an admin user that can
moderate the app.
> ✨ Add an admin user

- app/assets/stylesheets/application.tailwind.css
- app/javascript/application.js
- app/views/layouts/application.html.erb
- config/importmap.rb
- config/locales/en.yml
We have added an accordion to the nav menu to make it easy to navigate
between between article creation and viewing the created articles.
> ✨ Add accordion to nav menu

- app/views/articles/index.html.erb
- config/locales/en.yml
A user can now edit an article they are not happy with by clicking the
edit link on the article index page.
> ✨ User can edit the article

- app/views/passwords/new.html.erb
We have changed to an email_field in order to improve usability.
We have changed the CSS classes to be an array in order to make view
look neat.
> ♻️  Refactor reset password

- app/controllers/articles_controller.rb
- app/models/article.rb
- app/models/user.rb
- app/views/articles/show.html.erb
- config/locales/en.yml
- spec/models/article_spec.rb
- spec/models/user_spec.rb
- spec/system/user_creates_an_article_spec.rb
We have made quality of life improvements to improve code readability
and to make it easy to understand.
> ♻️  Refactor limit article edit

- app/assets/stylesheets/application.tailwind.css
- app/views/layouts/application.html.erb
- config/locales/en.yml
We have made some quality of life improvements to enhance the appearance
and the readability of the HTML, resulting in a prettier presentation.
> ♻️  Change HTML formatting

- app/controllers/articles_controller.rb
- spec/system/user_articles_spec.rb
We have added an ordering to the list of displayed articles to make it
more explicit.
We have changed the system test to make it easy to understand.
> ♻️  Refactor article index

- app/controllers/articles_controller.rb
- config/routes.rb
- spec/system/author_visits_the_home_page_spec.rb
- spec/system/guest_visits_the_home_page_spec.rb
- spec/system/user_articles_spec.rb
We have made it possible for someone without an account to be able to
view everyone's posts.
This was done so that the person may enjoy everyone's posts.
> ✨ Add a list of all articles to the home page

- app/controllers/users_controller.rb
- app/views/articles/_article.html.erb
- app/views/users/show.html.erb
- config/locales/en.yml
- spec/system/guest_visits_an_author_profile_spec.rb
Before, a guest wouldn't be able to view articles created by a user.
Now, a guest can simply navigate to any user's profile and they will
view the articles created by that user.
> ✨ Allow guest to view articles created by a user

- app/controllers/authors_controller.rb
- app/controllers/users_controller.rb
- app/views/authors/show.html.erb
- config/routes.rb
- spec/rails_helper.rb
- spec/system/author_visits_an_author_profile_spec.rb
- spec/system/guest_visits_an_author_profile_spec.rb
Previously, we were using the users controller to display the profile of the user but it was a bit confusing.
We have added the authors controller to handle user profiles. 
This change enhances code organization and improves readability.
> ✨ Add authors controller

- Gemfile.lock
https://github.com/rubygems/rubygems/releases/tag/bundler-v2.5.4
> Update Bundler to v2.5.4

- Gemfile.lock
https://github.com/rubygems/rubygems/releases/tag/bundler-v2.5.5
> Update Bundler to v2.5.5

- app/views/application/_flashes.html.erb
- config/tailwind.config.js
Before, we had duplication in the flash classes. We have refactored to remove the duplication from the partial.
> Refactor the flash classes

- app/controllers/articles_controller.rb
- app/controllers/comments_controller.rb
- app/models/article.rb
- app/models/comment.rb
- app/models/user.rb
- app/views/articles/index.html.erb
- app/views/articles/show.html.erb
- app/views/comments/_comment.html.erb
- app/views/comments/new.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20240703082434_create_comments.rb
- db/schema.rb
- spec/models/article_spec.rb
- spec/models/comment_spec.rb
- spec/models/user_spec.rb
- spec/system/author_visits_the_home_page_spec.rb
- spec/system/guest_visits_the_home_page_spec.rb
We are exploring letting users add comments to an article. For now, if a
user is able to add their opinion to an article that they find on the
platform.
> Add comments to the article

- Gemfile.lock
Upgrade gems to new versions based on updates from dependabot.
> Upgrade gems

- app/views/comments/_comment.html.erb
- app/views/comments/edit.html.erb
- app/views/comments/new.html.erb
- config/locales/en.yml
- spec/factories/comment.rb
- spec/system/author_visits_the_home_page_spec.rb
This refactor introduces no functional changes but improves the overall structure of the comment-related code.
We have made changes to make the code more understandable and thus improving maintainability.
> Refactor comment to improve readability

- app/views/comments/_comment.html.erb
Previously, the comments partial contained duplicate code.
This refactor simplifies the structure by ensuring only an individual comment is rendered.
> Refactor comments partial
